### ISSUE TITLE
No sign for annotation

### ISSUE THREAD

**Issue by fragov** [voldikss/coc-bookmark#14]
There are no signs in gutter for annotations (bookmarks with annotation), but for bookmarks only.

**Comment by voldikss** [comment]
Hi @fragov 
Could you upgrade and test again?

**Comment by Azumgi** [comment]
Works fine for me.

**Comment by voldikss** [comment]
Thanks @Azumgi for testing! I feel that the issue got fixed, so let me close this issue. 
@fragov If it still exists, feel free to reopen it.
