### ISSUE TITLE
Fuzzy search ignores file path for annotated bookmarks

### ISSUE THREAD

**Issue by Azumgi** [voldikss/coc-bookmark#15]
## Steps to reproduce

1. Create 2 bookmarks in a single file: regular and annotated.
2. Try to fuzzy search the file's name in the bookmark list.

You'll get only 1 match (regular bookmark).

## Expected behavior

Two bookmarks should show up.

Or is it intentional?

**Comment by voldikss** [comment]
Can not reproduce. Works normally for me.

**Comment by Azumgi** [comment]
Weird. This is how it looks for me:

![Peek 2020-06-14 14-06](https://user-images.githubusercontent.com/35058624/84591578-5549ce00-ae48-11ea-8ac3-9d372f5e9a57.gif)

If it's relevant:
- Neovim 4.3.0
- Linux
- All the plugins including coc.nvim are up to date

**Comment by voldikss** [comment]
Fixed, thanks for the report.

**Comment by Azumgi** [comment]
That was fast! Thank you.
