### ISSUE TITLE
why my bookmark doesn't show?

### ISSUE THREAD

**Issue by happysmile12321** [voldikss/coc-bookmark#16]
`  "bookmark.sign": {
    "type": "string",
    "default": "Note:",
    "description": "Bookmark icon for sign column"
},
"bookmark.signHl": {
  "type": "string",
  "default": "Tag",
  "description": "Highlight group for sign"
}
`
I add this to my cocconfig
and 
`"coc bookmark
nmap <Leader>j <Plug>(coc-bookmark-next)
nmap <Leader>k <Plug>(coc-bookmark-prev)
`
to my initvim,
but the bookmark doesn't show,so why this happen?

**Comment by voldikss** [comment]
No idea about this

**Comment by yoo** [comment]
@happysmile12321 I had the same problem. The default highlight group "Tag" did not show for me. First if you use some sort of UTF-8 glyph make sure vim can display it. Second change the highlight group to something you like. You can display the highlight groups by running `:so $VIMRUNTIME/syntax/hitest.vim` [1] and choose something you like. 
My configuration:
```json
{
  "bookmark.sign": ">",
  "bookmark.signHl": "Todo"
}
```
[1] https://jordanelver.co.uk/blog/2015/05/27/working-with-vim-colorschemes/
