### ISSUE TITLE
Bookmarks do not follow the move

### ISSUE THREAD

**Issue by pacmanzou** [voldikss/coc-bookmark#18]
你好，
比如我在200行打了书签标记，当我删减前面1-199的某几行时，显示的标记虽然也正确（还在目标代码上），
但是当我执行`CocCommand bookmark.next`时,它实际跳转的还是在当前的200行位置，然而我的目标代码已经移动到了上面，它是按照记录的行号来显示标记的吗？ 如何让它和vim里面的m标记一样正确的跟随移动呢?

**Comment by voldikss** [comment]
目前唯一的解决办法是
跳到其他buffer再跳回来，这样可以触发 `BufEnter` 方法，使标记更新（https://github.com/voldikss/coc-bookmark/blob/39a5bc0affc90fc1e21e511179d1b8434be40d10/src/index.ts#L35-L37）
关于buffer改动之后如何更新标记，我暂时还没找到一个轻松的解决办法，后面我有空再尝试解决（https://github.com/voldikss/coc-bookmark/blob/39a5bc0affc90fc1e21e511179d1b8434be40d10/src/index.ts#L39-L47）

**Comment by voldikss** [comment]
closed by 7d84965
